spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE # "lb" means "load balance" via Eureka
          predicates:
            - Path=/api/users/, /api/auth/** # Match these URL patterns
