
spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/cohero_users
    username: postgres # <-- CHANGE THIS
    password: "0000"
    driver-class-name: org.postgresql.Driver
  
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 0



eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  
